### ISSUE TITLE
Lockfile not present in root

### ISSUE THREAD

**Issue by rustaceanrob** [bitcoindevkit/bitcoin-ffi#21]
`Cargo.toml` is not committed in the root directory but it is within `uniffi-bindgen`. We should either ignore lock files in `gitignore` or commit it. Many LSPs will build the root lockfile automatically

**Comment by thunderbiscuit** [comment]
Yeah my understanding is roughly that for applications/binaries, it's usually better to add the lockfile, and for libraries to leave it out?

I'm ok with removing the lockfiles in this case.
